global:
  scrape_interval: 15s
  evaluation_interval: 15s # Tần suất Prometheus kiểm tra các quy tắc cảnh báo (Alert Rules)

# Khai báo kết nối tới Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093' # Tên service alertmanager trong docker-compose

# Chỉ định đường dẫn chứa các tệp quy tắc cảnh báo
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Cấu hình danh sách các service cần thu thập metric (Scrape Configs)
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysql-exporter:9104']